export default {
  motorZPPCheckIfMotorZPPIsApplicableDescription: 'Check if there is voluntary anal contraction (VAC)',
  motorZPPCheckIfMotorZPPIsApplicableYesAction: 'VAC is set to "Yes". We set the Motor ZPP to "NA" and stop',
  motorZPPCheckIfMotorZPPIsApplicableNTAction: 'VAC is set to "NT". We set the Motor ZPP to "NA" and we proceed to determine the Top and Bottom levels.',
  motorZPPCheckIfMotorZPPIsApplicableNoAction: 'VAC is set to "No". We proceed to determine the Top and Bottom levels.',
  motorZPPCheckLowerNonKeyMuscleDescription: 'Check for motor function on the lowest non-key muscle.',
  motorZPPCheckLowerNonKeyMuscleConsiderAction: 'Consider non-key muscle with motor function when calculating the Motor ZPP',
  motorZPPCheckLowerNonKeyMuscleDoNotConsiderAction: 'The lowest non-key muscle does not have an effect on the AIS calculation on this side.',
  motorZPPGetTopAndBottomLevelsForCheckDescription: 'Using the Motor Levels, look for the top and bottom levels to examine. We will move from bottom to top using that range.',
  motorZPPGetTopAndBottomLevelsForCheckRangeAction: 'Our search range will be between {{bottom}} (bottom) and {{top}} (top).',
  motorZPPGetTopAndBottomLevelsForCheckIncludeTLAction: 'Since T1 is a normal Motor Level, we include thoracic and lumbar dermatomes in our test.',
  motorZPPGetTopAndBottomLevelsForCheckDoNotIncludeTLAction: 'Since T1 is not a normal Motor Level, we do not include thoracic and lumbar dermatomes in our test.',
  motorZPPGetTopAndBottomLevelsForCheckIncludeS10OrLowerAction: 'Since S1 is a normal Motor Level, the bottom of our range is determined by the lowest Motor Level.',
  motorZPPGetTopAndBottomLevelsForCheckDoNotIncludeS10OrLowerAction: 'Since S1 is not a normal Motor Level, we make S1 the bottom of our range.',
  motorZPPCheckForMotorFunctionDescription: 'Check for motor function on {{levelName}}: {{motor}}.',
  motorZPPCheckForMotorFunctionNonKeyMuscleOverrideAndStopAction: 'Motor function was found but the lowest non-key muscle with motor function overrides it as it affects the AIS calculation for this case. We stop iterating.',
  motorZPPCheckForMotorFunctionAddLevelAndStopAction: 'Motor function was found. We include the level in Motor ZPP and stop iterating.',
  motorZPPCheckForMotorFunctionFunctionFoundButKeyMuscleOverrideAction:
    'Motor function marked as not normal was found but the lowest non-key muscle with motor function overrides it as it affects the AIS calculation for this case. We continue iterating.',
  motorZPPCheckForMotorFunctionStopAtTopAction: 'Because we have reached the top level in our range, we stop.',
  motorZPPCheckForMotorFunctionContinueUntilTopAction: 'Since we have not reached the top level of our range, we continue',
  motorZPPCheckForMotorFunctionAddStarAction: 'Since motor has a star on this level or above, we add a star to the result.',
  motorZPPCheckForMotorFunctionAddLevelWithNormalFunctionAndContinue: 'Motor function marked as not normal was found. We include the level in Motor ZPP and continue.',
  motorZPPCheckForMotorFunctionNoFunctionFoundContinueAction: 'No motor function was found. We continue.',
  motorZPPCheckForMotorFunctionTopOfRangeReachedStopAction: 'We reached the top of the searchable range. We stop iterating. Next we will check the lowest non-key muscle with motor function.',
  motorZPPCheckForSensoryFunctionDescription: 'Check for sensory function on {{levelName}} (LT: {{lightTouch}} - PP: {{pinPrick}})',
  motorZPPCheckForSensoryFunctionLevelIncludedInMotorValuesAction: '{{levelName}} is included in motor values.',
  motorZPPCheckForSensoryFunctionLevelIncludedButOverriddenByNonKeyMuscleAction: 'The value, however is overridden by the non-key muscle',
  motorZPPCheckForSensoryFunctionAddLevelAndContinueAction: 'We add it to Motor ZPP and continue checking.',
  motorZPPCheckForSensoryFunctionTopOfRangeReachedStopAction: 'We are a the top of the range, we stop.',
  motorZPPCheckForSensoryFunctionNoSensoryFunctionFoundContinueAction: 'No sensory function was found. We continue.',
  motorZPPSortMotorZPPDescription: 'Sort Motor ZPP',
  motorZPPSortMotorZPPEnsureNAIsPlacedFirstAction: 'Ensure "NA" is placed first',
  motorZPPAddLowerNonKeyMuscleToMotorZPPIfNeededDescription: 'If the non-key muscle affects the AIS calculations, we add it to Motor ZPP.',
  motorZPPAddLowerNonKeyMuscleToMotorZPPIfNeededAddNonKeyMuscleAction: 'We add the lowest non-key muscle with motor function to the Motor ZPP',
  motorZPPAddLowerNonKeyMuscleToMotorZPPIfNeededIgnoreNonKeyMuscleAction: 'The lowest non-key muscle either does not have an effect on the AIS or has already been added to Motor ZPP.'
};
